[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"
###Configurations for more user store types
#connection_url = "ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}"
#connection_name = "uid=admin,ou=system"
#connection_password = "admin"
#base_dn = "dc=wso2,dc=org"
[user_store.properties]
CaseInsensitiveUsername = "{is_case_insensitive_username_and_attributes}"
CaseInsensitiveAttributes = "{is_case_insensitive_username_and_attributes}"
UseCaseSensitiveUsernameForCacheKeys = false
SCIMEnabled=true
IsBulkImportSupported=false

[realm_manager]
data_source = "WSO2USER_DB"

[database.identity_db]
driver = "{db_driver}"
url = "{identity_db_url}"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.identity_db.pool_options]
maxActive = "1500"
defaultAutoCommit={identity_default_auto_commit}
testOnBorrow = true
testWhileIdle = true
validationInterval="30000"
maxWait = "60000"
minIdle = "5"
validationQueryTimeout="1"
commitOnReturn=false

[database.shared_db]
driver = "{db_driver}"
url = "{reg_db_url}"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.shared_db.pool_options]
maxActive = "1500"
defaultAutoCommit=false
testOnBorrow = true
testWhileIdle = true
validationInterval="30000"
maxWait = "60000"
minIdle = "5"
validationQueryTimeout="1"
commitOnReturn=false

[database.user]
driver = "{db_driver}"
url = "{user_db_url}"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.user.pool_options]
maxActive = "1500"
defaultAutoCommit=false
testOnBorrow = true
testWhileIdle = true
validationInterval="30000"
maxWait = "60000"
minIdle = "5"
validationQueryTimeout="1"
commitOnReturn=false

[session]
data_source="jdbc/WSO2SessionDB"

[datasource.WSO2SessionDB]
id = "WSO2SessionDB"
url = "{session_db_url}"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
driver = "{db_driver}"
jmxEnabled = false
[datasource.WSO2SessionDB.pool_options]
maxActive = "1500"
defaultAutoCommit=false
testOnBorrow = true
testWhileIdle = true
validationInterval="30000"
maxWait = "60000"
minIdle = "5"
validationQueryTimeout="1"
commitOnReturn=false

[transport.https.properties]
maxThreads = "750"
acceptCount = "750"

[authentication.consent]
prompt = true

[admin_service]
wsdl.enable=false

[keystore.primary]
file_name = "wso2carbon{keystore_extension}"
password = "wso2carbon"
type="{keystore_type}"

[truststore]
file_name="client-truststore{keystore_extension}"
password="wso2carbon"
type="{keystore_type}"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

# The KeyStore which is used for encrypting/decrypting internal data. By default the primary keystore is used as the internal keystore.

#[keystore.internal]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

# The KeyStore which is used for tls communication. By default the primary keystore is used as the tls keystore.

#[keystore.tls]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

#Google reCAPTCHA settings.

#[recaptcha]
#enabled = true
#api_url = "https://www.google.com/recaptcha/api.js"
#verify_url = "https://www.google.com/recaptcha/api/siteverify"
#site_key = ""
#secret_key = ""

# SMTP email sender settings.
#[output_adapter.email]
#from_address= "abcd@gmail.com"
#username= "abcd"
#password= "xxxx"
#hostname= "smtp.gmail.com"
#port= 587

[clustering]
#membership_scheme = true
#domain = "is590.qa.com"
membership_scheme = "wka"
local_member_host = "member_ip_1"
localMemberPort = "4000"
members = ["member_ip_3:4000", "member_ip_2:4000", "member_ip_1:4000"]

[oauth.grant_type.jwt]
iat_validity_period=1440

[[oauth.custom_grant_type]]
name="urn:ietf:params:oauth:grant-type:token-exchange"
grant_handler="org.wso2.carbon.identity.oauth2.grant.token.exchange.TokenExchangeGrantHandler"
grant_validator="org.wso2.carbon.identity.oauth2.grant.token.exchange.TokenExchangeGrantValidator"
[oauth.custom_grant_type.properties]
IdTokenAllowed=true
IATValidityPeriod="86400"
